/* ==========================================================================
   CARGA INICIAL DE DADOS - SIMULAÇÃO DE CATÁLOGO (RF#09)
   ========================================================================== */

INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'O Codificador Solitário', 'FILME', 2024, 120, 9.50, 'Um arquiteto de software tenta salvar um sistema legado antes do prazo final, enfrentando débitos técnicos letais.', 'Ficção Científica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'Sprint Mortal', 'SERIE', 2023, 45, 8.80, 'Uma equipe ágil descobre que cada bug não resolvido no sistema tem consequências perigosas no mundo real.', 'Suspense', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'A Vingança do QA', 'FILME', 2025, 95, 7.20, 'Ele avisou que o código ia quebrar em produção, ninguém ouviu. Agora, os scripts de testes automatizados ganharam vida própria.', 'Terror', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'Amor em Tempo de Compilação', 'FILME', 2022, 110, 8.10, 'Dois desenvolvedores seniores se apaixonam resolvendo conflitos de merge em um repositório open-source.', 'Romance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'Senhor dos Containers: A Sociedade do Docker', 'FILME', 2021, 180, 9.90, 'Um jovem engenheiro DevOps precisa transportar uma imagem corrompida até o servidor de produção na montanha da AWS.', 'Aventura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'Stranger Pings', 'SERIE', 2020, 50, 9.10, 'Quando os servidores de DNS caem na cidade, um grupo de jovens descobre um gateway físico para a deep web.', 'Ficção Científica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'O Lobo do Vale do Silício', 'FILME', 2023, 140, 8.50, 'A ascensão e queda frenética do CEO de uma startup que prometeu revolucionar o mercado com uma IA que não existia.', 'Drama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'De Volta para o Backup', 'FILME', 2019, 116, 9.00, 'Um programador viaja no tempo desesperadamente para impedir o estagiário de rodar um DROP TABLE sem a cláusula WHERE.', 'Comédia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'As Crônicas de Java: O Leão, a Feiticeira e o NullPointer', 'FILME', 2024, 135, 8.70, 'Quatro desenvolvedores juniores descobrem um portal no servidor local que os leva a um mundo mágico sem tipagem forte.', 'Fantasia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO filme (id, titulo, tipo, ano, duracao_minutos, relevancia, sinopse, genero, criado_em, atualizado_em) VALUES (RANDOM_UUID(), 'Breaking Bug', 'SERIE', 2018, 60, 9.80, 'Um professor de algoritmos falido começa a escrever ransomwares altamente sofisticados para pagar seu tratamento médico.', 'Drama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);